"""initial schema

Revision ID: 1a8e9062d137
Revises: 
Create Date: 2026-09-19 12:25:52.202780

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


revision = '1a8e9062d137'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('visibility', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('share_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('win_points', sa.Integer(), nullable=False),
    sa.Column('draw_points', sa.Integer(), nullable=False),
    sa.Column('loss_points', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_group_share_token'), ['share_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_group_slug'), ['slug'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('groupowner',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'user_id')
    )
    op.create_table('player',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'name', name='uq_player_group_name')
    )
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_player_group_id'), ['group_id'], unique=False)

    op.create_table('session',
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_user_id'), ['user_id'], unique=False)

    op.create_table('venue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'name', name='uq_venue_group_name')
    )
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_venue_group_id'), ['group_id'], unique=False)

    op.create_table('matchday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('mvp_player_id', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['mvp_player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venue.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('matchday', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matchday_group_id'), ['group_id'], unique=False)

    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matchday_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('sort_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['matchday_id'], ['matchday.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_team_matchday_id'), ['matchday_id'], unique=False)

    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('matchday_id', sa.Integer(), nullable=False),
    sa.Column('sort_index', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=False),
    sa.Column('away_score', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['matchday_id'], ['matchday.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_match_away_team_id'), ['away_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_home_team_id'), ['home_team_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_match_matchday_id'), ['matchday_id'], unique=False)

    op.create_table('teammember',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('teammember', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_teammember_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_teammember_team_id'), ['team_id'], unique=False)

    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('own_goal', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_goal_match_id'), ['match_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goal_player_id'), ['player_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_goal_team_id'), ['team_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goal', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_goal_team_id'))
        batch_op.drop_index(batch_op.f('ix_goal_player_id'))
        batch_op.drop_index(batch_op.f('ix_goal_match_id'))

    op.drop_table('goal')
    with op.batch_alter_table('teammember', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_teammember_team_id'))
        batch_op.drop_index(batch_op.f('ix_teammember_player_id'))

    op.drop_table('teammember')
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_match_matchday_id'))
        batch_op.drop_index(batch_op.f('ix_match_home_team_id'))
        batch_op.drop_index(batch_op.f('ix_match_away_team_id'))

    op.drop_table('match')
    with op.batch_alter_table('team', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_team_matchday_id'))

    op.drop_table('team')
    with op.batch_alter_table('matchday', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matchday_group_id'))

    op.drop_table('matchday')
    with op.batch_alter_table('venue', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_venue_group_id'))

    op.drop_table('venue')
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_user_id'))

    op.drop_table('session')
    with op.batch_alter_table('player', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_player_group_id'))

    op.drop_table('player')
    op.drop_table('groupowner')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))

    op.drop_table('user')
    with op.batch_alter_table('group', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_group_slug'))
        batch_op.drop_index(batch_op.f('ix_group_share_token'))

    op.drop_table('group')
    # ### end Alembic commands ###
